hydra:
  run:
    dir: outputs/qa_agent_inference/${dataset.data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory

defaults:
  - _self_
  - doc_ranker: topk_ranker  #idf_topk_ranker # The document ranker to use
  - agent_prompt: itc_ircot # The agent prompt to use
  - qa_prompt: itc # The QA prompt to use
  - ner_model: llm_ner_model # The NER model to use
  - el_model: itc_nomic_ai # The EL model to use
  - qa_evaluator: hotpotqa # The QA evaluator to use

seed: 1024

dataset:
  root: ../../bbdd # data root directory (relativo a gfm-rag-main/)
  data_name: data_name # data name

llm:
  _target_: gfmrag.llms.Gemini # The language model to use
  model_name_or_path: gemini-2.5-pro # The model name or path gemini-2.0-flash-lite
  retry: 5 # Number of retries

graph_retriever:
  model_path: outputs/qa_finetune/2025-11-26/12-45-31/pretrained_best # Checkpoint path (relativo a gfm-rag-main/)
  doc_ranker: ${doc_ranker} # The document ranker to use
  ner_model: ${ner_model} # The NER model to usek
  el_model: ${el_model} # The EL model to use
  qa_evaluator: ${qa_evaluator} # The QA evaluator to use
  init_entities_weight: True # Whether to initialize the entities weight

test:
  top_k: 10 # Number of documents to retrieve
  max_steps: 2 # Maximum number of steps
  max_test_samples: -1 # -1 for all samples
  resume: null # Resume from previous prediction
