name: Python Publish (pypi)
on:
  workflow_dispatch:
  release:
    types: [published ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gfmrag
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-tags: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v3
        with:
            path: .venv
            key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
        run: uv sync --no-group dev --no-group doc
        #----------------------------------------------

      - name: Export Publication Version
        run: echo "version=`python -c 'import tomllib; f=open(\"pyproject.toml\",\"rb\"); print(tomllib.load(f)[\"project\"][\"version\"])'`" >> $GITHUB_OUTPUT

      - name: Build Distributable
        shell: bash
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
          verbose: true
